---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Ontwerp en programmeer je eigen RPG doolhofspel.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Inleiding: '
  - 
    title: Voeg nieuwe kamers toe
  - 
    title: 'Uitdaging: voeg meer kamers toe'
  - 
    title: Voorwerpen toevoegen om te verzamelen
  - 
    title: 'Uitdaging: voeg nieuwe voorwerpen toe'
  - 
    title: Vijanden toevoegen
  - 
    title: 'Uitdaging: meer monsters toevoegen'
  - 
    title: Het spel winnen
  - 
    title: 'Uitdaging: ontwikkel je eigen spel'
