---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: Escape the maze
description: Design and code your own maze escape text-based game.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2025-01-02
steps:
- title: What you will make
- title: Add a new room
  completion:
  - engaged
- title: Add items to collect
- title: Add enemies
- title: Winning the game
  completion:
  - internal
  - external
- title: Challenge
  challenge: true