---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: अपनी स्वयं की RPG भूल-भूलैया गेम को डिज़ाइन और कोड करें।
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: project
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: परिचय
- title: नए कमरे जोड़ना
- title: 'चुनौती: नए कमरे जोड़ें'
  challenge: true
- title: एकत्र करने के लिए आइटम्स जोड़ना
  completion:
  - engaged
- title: 'चुनौती: नए आइटम्स जोड़ें'
  challenge: true
- title: दुश्मन जोड़ना
- title: 'चुनौती: और दैत्य जोड़ना'
  challenge: true
- title: गेम जीतना
  completion:
  - internal
  challenge: true