---
hero_image: images / rpg.png
theme: marinha
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Projetar e codificar seu próprio jogo de labirinto de RPG.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction'
  - 
    title: Adicionando novos quartos
  - 
    title: 'Desafio: adicionar novos quartos'
    challenge: true
  - 
    title: Adicionando itens para coletar
  - 
    title: 'Desafio: adicionar novos itens'
    challenge: true
  - 
    title: Adicionando inimigos
  - 
    title: 'Desafio: Adicionando mais monstros'
    challenge: true
  - 
    title: Ganhando o jogo
  - 
    title: 'Desafio: desenvolva seu próprio jogo'
    challenge: true
