---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Dizajniraj i napravi vlastitu RPG igru labirinta.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Uvod
- title: Dodavanje novih prostorija
- title: 'Izazov: Dodaj nove prostorije'
  challenge: true
- title: Dodavanje predmeta za sakupljanje
  completion:
  - engaged
- title: 'Izazov: Dodaj nove predmete'
  challenge: true
- title: Dodavanje neprijatelja
- title: 'Izazov: Dodaj još čudovišta'
  challenge: true
- title: Pobjeda u igri
  completion:
  - internal
- title: 'Izazov: Osmisli vlastitu igru'
  challenge: true
