---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Konzipiere und programmiere dein eigenes RPG-Labyrinth - Spiel.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
- title: Einleitung
- title: Neue Zimmer hinzufügen
- title: 'Herausforderung: Neue Zimmer hinzufügen'
  challenge: true
- title: Gegenstände zum Einsammeln hinzufügen
  completion:
  - engaged
- title: 'Herausforderung: Neue Gegenstände hinzufügen'
  challenge: true
- title: Feinde (Monster) hinzufügen
- title: 'Herausforderung: Noch mehr Monster hinzufügen'
  challenge: true
- title: Das Spiel gewinnen
  completion:
  - internal
- title: 'Herausforderung: Entwickle dein eigenes Spiel'
  challenge: true
