---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Proiectează-ți si programează-ți propriul joc labirint RPG.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: jocuri
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introducere'
  - 
    title: Adăugarea de camere noi
  - 
    title: 'Provocare: Adaugă camere noi'
    challenge: true
  - 
    title: Adăugarea de itemi de colectat
  - 
    title: 'Provocare: Adaugă noi itemi'
    challenge: true
  - 
    title: Adăugarea oponenților
  - 
    title: 'Provocare: Adăugarea mai multor monștri'
    challenge: true
  - 
    title: Cum să câștigi jocul
  - 
    title: 'Provocare: Programează-ți propriul joc'
    challenge: true
