---
hero_image: images/rpg.png
theme: marynarka wojenna
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Zaprojektuj i zakoduj swoją własną labiryntową grę RPG.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Wprowadzenie'
  - 
    title: Dodawanie nowych pokoi
  - 
    title: 'Wyzwanie: Dodaj nowe pokoje'
    challenge: true
  - 
    title: Dodawanie przedmiotów do zebrania
  - 
    title: 'Wyzwanie: Dodaj nowe przedmioty'
    challenge: true
  - 
    title: Dodawanie wrogów
  - 
    title: 'Wyzwanie: dodawanie kolejnych potworów'
    challenge: true
  - 
    title: Wygranie gry
  - 
    title: 'Wyzwanie: Napisz swoją własną grę'
    challenge: true
