---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Design and code your own RPG maze game.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: 2017-01-01
steps:
  - 
    title: 'Introduction: '
  - 
    title: Adding new rooms
  - 
    title: 'Challenge: Add new rooms'
  - 
    title: Adding items to collect
  - 
    title: 'Challenge: Add new items'
  - 
    title: Adding enemies
  - 
    title: 'Challenge: Adding more monsters'
  - 
    title: Winning the game
  - 
    title: 'Challenge: Develop your own game'
