---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, tasarım-0, programlama-1, fiziksel-hesaplama-0, üretim-0, topluluk-0
title: RPG
description: Design and code your own RPG maze game.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: oyunlar
technologies: python
site_areas: projeler
hardware: ''
software: python
version: 3
last_tested: 01/01/2017
steps:
  - 
    title: 'Giriş'
  - 
    title: Adding new rooms
  - 
    title: 'Challenge: Add new rooms'
    challenge: true
  - 
    title: Adding items to collect
  - 
    title: 'Challenge: Add new items'
    challenge: true
  - 
    title: Adding enemies
  - 
    title: 'Challenge: Adding more monsters'
    challenge: true
  - 
    title: Winning the game
  - 
    title: 'Challenge: Develop your own game'
    challenge: true
