---
hero_image: images/rpg.png
theme: navy
duration: 2
listed: true
ingredient: false
copyedit: false
curriculum: 1, design-0, programming-1, phys-comp-0, manufacture-0, community-0
title: RPG
description: Kendi RPG labirent oyununu tasarla ve kodla.
original_url: https://codeclubprojects.org/en-GB/python/rpg
interests: games
technologies: python
site_areas: projects
hardware: ''
software: python
version: 3
last_tested: "2017-01-01\n"
steps:
  - title: 'Giriş'
  - title: Yeni oda ekleme
  - title: 'Meydan okuma: Yeni odalar ekle'
    challenge: true
  - title: Toplamak için eşyalar ekleme
  - title: 'Meydan okuma: Yeni eşyalar ekle'
    challenge: true
  - title: Düşman ekleme
  - title: 'Meydan okuma: Daha fazla canavar ekle'
    challenge: true
  - title: Oyunu kazanma
  - title: 'Meydan Okuma: Kendi oyununu geliştir'
    challenge: true
